"""Paper-by-paper catalogue of 2025-26 speculative-decoding work (lit/papers_2026.{json,md}).

The records were collected by research agents into /tmp/lit2026/<group>.json (schema: /tmp/lit2026/SCHEMA.md);
this merges them into lit/papers_2026.json (the copy that is kept) and renders the markdown.

  python3 scripts/lit2026.py [--src /tmp/lit2026]
"""
import argparse
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GROUPS = {
    "A_parallel_drafters": "Parallel / block / diffusion drafters",
    "B_trees": "Token trees and tree sizing",
    "C_serving_rl_theory": "Serving policies, verification theory, RL rollouts",
    "D_acceptance": "Raising acceptance (training objectives, architectures, analyses)",
    "E_hybrid_numerics": "Hybrid / SSM verification and numerical exactness",
}


def cell(v, n=None):
    s = "—" if v in (None, "", []) else (", ".join(map(str, v)) if isinstance(v, list) else str(v))
    s = s.replace("|", "/").replace("\n", " ")
    return s if n is None or len(s) <= n else s[: n - 1] + "…"


def link(p):
    return f"[{p['short']}](https://arxiv.org/abs/{p['arxiv']})" if p.get("arxiv") else p["short"]


def yes(v):
    return isinstance(v, str) and v.strip().lower().startswith("yes")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="/tmp/lit2026")
    args = ap.parse_args()

    papers = []
    if os.path.isdir(args.src):
        for path in sorted(glob.glob(f"{args.src}/*.json")):
            group = os.path.basename(path)[:-5]
            for p in json.load(open(path)):
                papers.append(dict(p, group=group))
        seen = {}
        for p in papers:  # the same paper can come from two groups; keep the first, note the other
            key = p.get("arxiv") or p["short"].lower()
            if key in seen:
                seen[key].setdefault("also_in", []).append(p["group"])
            else:
                seen[key] = p
        papers = list(seen.values())
        json.dump(papers, open(f"{ROOT}/lit/papers_2026.json", "w"), indent=1)
    else:
        papers = json.load(open(f"{ROOT}/lit/papers_2026.json"))

    lines = ["# Speculative decoding 2025–26: paper-by-paper", "",
             "Generated by `scripts/lit2026.py` from `lit/papers_2026.json` (collected Oct 2026 from arXiv / OpenReview /"
             " GitHub). *Limitation* is the paper's own stated limitation where it has one, else the clearest scope limit"
             " in its experiments. **Long drafts** = does it specifically raise acceptance at later draft positions.", "",
             "| Paper | First version | Venue | Area | Long drafts | Max draft | Max batch |", "|---|---|---|---|---|---|---|"]
    for g in GROUPS:
        for p in sorted((p for p in papers if p["group"] == g), key=lambda p: p.get("first_version") or ""):
            lines.append(f"| {link(p)} | {cell(p.get('first_version'))} | {cell(p.get('venue'), 24)} | {g[0]} | "
                         f"{'yes' if yes(p.get('targets_deep_positions')) else 'no'} | "
                         f"{cell(p.get('max_draft_len_evaluated'))} | {cell(p.get('max_batch_evaluated'))} |")
    lines.append("")
    lines.append("Areas: " + "; ".join(f"**{g[0]}** {lbl}" for g, lbl in GROUPS.items()))
    for g, label in GROUPS.items():
        group = sorted((p for p in papers if p["group"] == g), key=lambda p: p.get("first_version") or "")
        if not group:
            continue
        lines += ["", f"## {g[0]}. {label}", ""]
        for p in group:
            lines += [f"### {p['short']} — {cell(p.get('title'))}",
                      f"*{cell(p.get('arxiv') and 'arXiv ' + p['arxiv'])} · {cell(p.get('first_version'))} · "
                      f"{cell(p.get('venue'))}* · builds on: {cell(p.get('builds_on'))}", "",
                      f"- **Problem:** {cell(p.get('problem'))}",
                      f"- **Contribution:** {cell(p.get('contribution'))}",
                      f"- **Limitation:** {cell(p.get('limitation'))}",
                      f"- **Evaluated:** draft ≤ {cell(p.get('max_draft_len_evaluated'))}, batch ≤ "
                      f"{cell(p.get('max_batch_evaluated'))}; acceptance length {cell(p.get('reported_tau'))}",
                      f"- **Long drafts:** {cell(p.get('targets_deep_positions'))}"
                      + (f" · per-position data: {cell(p.get('per_position_analysis'))}"
                         if p.get("per_position_analysis") else ""), ""]
            if p.get("notes"):
                lines.insert(len(lines) - 1, f"- *Note:* {cell(p['notes'])}")
    open(f"{ROOT}/lit/papers_2026.md", "w").write("\n".join(lines) + "\n")
    print(f"{len(papers)} papers -> lit/papers_2026.json, lit/papers_2026.md")


if __name__ == "__main__":
    main()
